# MySQL
development:
  adapter: mysql
  encoding: utf8
  database: pisapp_dev
  username: pisapp
  password: P1sApp@10

test:
  adapter: mysql
  encoding: utf8
  database: pisapp_test
  username: pisapp
  password: P1sApp@10

production:
  adapter: mysql
  encoding: utf8
  database: pisapp
  username: pisapp
  password: P1sApp@10
